godfreystore/views.py
from flask import Blueprint, render_template, url_for, request, session, flash, redirect, abort
from .models import ProductDetail, Product, Order, orderdetails
from datetime import datetime
from .forms import CheckoutForm
from . import db




main_bp = Blueprint('main', __name__)

@main_bp.route('/')
def index():
    products = db.session.scalars(db.select(Product).order_by(Product.id)).all()
    return render_template('index.html', products=products)


# View the product detail page
@main_bp.route('/item/<int:product_id>')
def item(product_id):
    product = db.session.query(Product).get(product_id)
    return render_template('item.html', product=product)

# Search Result
@main_bp.route('/search')
def search():
    search = request.args.get('search')
    search = '%{}%'.format(search)
    product = Product.query.filter(Product.productname.like(search)).all()
    if not product:
        abort(404)
    return render_template('search.html', product=product )

@main_bp.route('/categories/<category>')
def categories(category):
    product = Product.query.filter(Product.product_category.like(category)).all()
    cat = product[0].product_category
    print(cat)
    if not product:
        abort(404)
    return render_template('categorised-item.html', cat=cat, product=product )

# Referred to as "Basket" to the user
@main_bp.route('/order', methods=['POST', 'GET'])
def order():
    product_id = request.values.get('product_id')
    print(f'Values: {product_id}')
    # retrieve order if there is one
    if 'order_id' in session.keys():
        order = db.session.scalar(db.select(Order).where(Order.id==session['order_id']))
        # order will be None if order_id/session is stale
    else:
        # there is no order
        order = None

    # create new order if needed
    if order is None:
        order = Order(status=False, firstname='', surname='', email='', phone='', totalcost=0, date=datetime.now())
        try:
            db.session.add(order)
            db.session.commit()
            session['order_id'] = order.id
        except:
            print('Failed trying to create a new order!')
            order = None
    
    # calculate total price
    total_price = 0
    if order is not None:
        for product in order.products:
            total_price += product.price
    
    # are we adding an item?
    if product_id is not None and order is not None:
        product = db.session.scalar(db.select(Product).where(Product.id==product_id))
        if product not in order.products:
            try:
                order.products.append(product)
                db.session.commit()
            except:
                flash('There was an issue adding the item to your basket',category='danger')
            return redirect(url_for('main.order'))
        else:
            flash('The selected item has been added into cart already',category='warning')
            return redirect(url_for('main.order'))
    return render_template('order.html', order=order, total_price=total_price)

# Delete specific basket items
# Note this route cannot accept GET requests now
@main_bp.route('/deleteorderitem', methods=['POST'])
def deleteorderitem():
    id = request.form['id']
    if 'order_id' in session:
        order = db.get_or_404(Order, session['order_id'])
        product_to_delete = db.session.scalar(db.select(Product).where(Product.id==id))
        try:
            order.products.remove(product_to_delete)
            db.session.commit()
            return redirect(url_for('main.order'))
        except:
            return 'Problem deleting item from order'
    return redirect(url_for('main.order'))

# Scrap basket
@main_bp.route('/deleteorder')
def deleteorder():
    if 'order_id' in session:
        del session['order_id']
        flash('The shopping cart is cleared',category='danger')
    return redirect(url_for('main.index'))

# Complete the order
@main_bp.route('/checkout', methods=['POST','GET'])
def checkout():
    form = CheckoutForm() 
    if 'order_id' in session:
        order = db.get_or_404(Order, session['order_id'])
        if form.validate_on_submit():
            order.status = True
            order.firstname = form.firstname.data
            order.surname = form.surname.data
            order.email = form.email.data
            order.phone = form.phone.data
            order.shippingaddress = form.shippingaddress.data
            total_cost = 0
            for product in order.products:
                total_cost += product.price
            order.totalcost = total_cost
            order.date = datetime.now()
            try:
                db.session.commit()
                del session['order_id']
                flash('Thanks for your order, the products will be shipped within 3-5 days',category='success')
                return redirect(url_for('main.index'))
            except:
                return 'There was an issue completing your order'
    return render_template('checkout.html', form=form)

godfreystore/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="description" content="eCommerce">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Godfrey's Store</title>
    <link rel="icon" href="{{ url_for('static', filename='img/logo.png') }}" type="image/png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}"/> 
</head>

<body>

    <!-- Contains the heading, navigation and banner image -->
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div style="margin-right:15px">
                <img style="height: 40px" src="{{ url_for('static', filename='img/logo.png') }}" alt="Logo">
            </div>
            <a class="navbar-brand" href="{{url_for('main.index')}}">GODFREY's</a>
          
            <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
              <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active">
                  <a class="nav-link" href="{{url_for('main.index')}}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <div class="dropdown">
                        <a class="nav-item nav-link dropdown-toggle active" data-toggle="dropdown" id="bookDropdown"
                            aria-haspopup="true" aria-expanded="false" href="#">Categories</a>
                        <div class="dropdown-menu" aria-labelledby="bookDropdown">
                            <a class="dropdown-item" href="{{ url_for('main.categories', category='Car GPS') }}">Car GPS</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{{ url_for('main.categories', category='Cycling GPS')}}">Cycling GPS</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{{ url_for('main.categories', category='Fitness Watches')}}">Fitness Watches</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item disabled" href="#">Fish Finder (Coming Soon)</a>
                        </div>
                </li>
              </ul>
                <a href="{{ url_for('main.order') }}">
                    <button type="button" class="btn btn-outline-success my-2 my-sm-0"><i class="bi bi-bag"></i> Shopping cart</button>
                </a>
            </div>
          </nav>

          {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            {% for category, message in messages %}
              <div class="alert alert-{{ category }} m-2 fade-out-alert" role="alert">
                  {{message}}
              </div>
            {% endfor %}
          {% endif %}
          {% endwith %} 
  
          

          {% block head %}
        
          {% endblock %}
        </header>

        <div class="container-fluid center-container">
            <main>
                {% block main %}
                
                {% endblock %}
            </main>
        </div>

    <!-- Footer of the website -->
    <footer class="footer">

        <div class="text-center py-2 bg-secondary">
            <div class="row">
                <div class="col-md-12 col-lg-4">
                    <img class="align-middle icon-size" src="{{ url_for('static', filename='img/logo.png') }}" alt="Logo">
                    <a class="navbar-brand">GODFREY's</a>
                </div>
                <div class="col-md-12 col-lg-4 ">
                    <a class="navbar-brand">Australia’s best GPS retailer.</a>
                </div>
                <div class="col-md-12 col-lg-4 text-center">
                    <img class="align-middle icon-size" src="{{ url_for('static', filename='img/footer-icon1.svg') }}" alt="icon">
                    <img class="align-middle icon-size" src="{{ url_for('static', filename='img/footer-icon2.svg') }}" alt="icon">
                    <img class="align-middle icon-size" src="{{ url_for('static', filename='img/footer-icon3.svg') }}" alt="icon">
                    <img class="align-middle icon-size" src="{{ url_for('static', filename='img/footer-icon4.png') }}" alt="icon">
                </div>
            </div>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    
</body>

</html>

godfreystore/templates/categorised-item.html
{% extends 'base.html' %}

{% block main %}
     <!-- Contains the main content of the website, divided into sections -->

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ url_for('main.index') }}">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{cat}}</li>
            </ol>
        </nav> 
        <section class="m-3">
            <div class="category-title-parent">
                {% for product in product%}
                <h1 class="category-title">{{product.product_category}}</h1>
                {% endfor %}
            </div>
            <div class="container-fluid">
                <div class="row">
                    {% for product in product%}
                            <div class="col-md-6 col-lg-3 mt-3">
                                <article class="card withCSS h-100">
                                    <a href="{{ url_for('main.item', product_id=product.product_detail_id) }}">
                                        <img class="card-img-top card-image"
                                        src="{{url_for('static', filename = 'img/'+product.image)}}"
                                        alt="{{product.productname}}">
                                    </a>
                                    <div class="card-body">
                                        <h3 class="card-title">{{product.productname}}</h3>
                                        <h5 class="card-text text-success font-weight-light">Stock Status: {{product.stock_status}}</h5>
                                        <h5 class="card-text font-italic">${{"%.2f"|format(product.price)}}</h5>
                                    </div>
                                    <div class="card-footer">
                                        <form action="{{url_for('main.order')}}">
                                            <input type="hidden" id="product_id" name="product_id" value="{{product.id}}">
                                            <input class="btn btn-success card-button-CSS" type="submit" value="Add to Cart">
                                        </form>
                                    </div>
                                </article>
                            </div>
                    {% endfor %}
                </div>
        </section>
{% endblock %}

godfreystore/templates/index.html
{% extends 'base.html' %}

{% block head %}
        <!--Jumbotron for Hero Section -->
        <div class="jumbotron jumbotron-fluid card jumbotron-background">
            <div class="row justify-content-center mt-5 pb-4">
                <div class="col-md-8">
                    <div class="jumbotron jumbotron-div shadow py-4 mb-5 ">
                        <h1 class="text-center jumbotron-title">Find your best GPS products</h1>
                            <form class="row justify-content-center form-inline my-2 my-lg-0" action="{{url_for('main.search')}}">
                                <input class="form-control search-box" type="search" placeholder="Search Products" aria-label="Search" name="search">
                                <button class="btn search-btn" type="submit">Search</button>
                            </form>
                    </div>
                </div>
            </div>
        </div> <!-- hero section -->
{% endblock %}


{% block main %}
     <!-- Contains the main content of the website, divided into sections -->
        <section class="m-3">
            <div class="category-title-parent">
                <h1 class="category-title" id="car-gps">Car GPS</h1>
            </div>

            <div class="container-fluid">
                <div class="row">
                    {% for product in products%}
                        {% if product.product_category == 'Car GPS' %}
                            <div class="col-md-6 col-lg-3">
                                <article class="card withCSS h-100">
                                    <a href="{{ url_for('main.item', product_id=product.product_detail_id) }}">
                                        <img class="card-img-top card-image"
                                        src="{{url_for('static', filename = 'img/'+product.image)}}"
                                        alt="{{product.productname}}">
                                    </a>
                                    <div class="card-body">
                                        <h3 class="card-title">{{product.productname}}</h3>
                                        <h5 class="card-text text-success font-weight-light">Stock Status: {{product.stock_status}}</h5>
                                        <h5 class="card-text font-italic">{{"$%.2f"|format(product.price)}}</h5>
                                    </div>
                                    <div class="card-footer">
                                        <form action="{{url_for('main.order')}}">
                                            <input type="hidden" id="product_id" name="product_id" value="{{product.id}}">
                                            <input class="btn btn-success card-button-CSS" type="submit" value="Add to Cart">
                                        </form>
                                    </div>
                                </article>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
        </section>


        <section class="m-3">
            <div class="category-title-parent">
                <h1 class="category-title" id="cycling-gps">Cycling GPS</h1>
            </div>

            <div class="container-fluid">
                <div class="row">
                    {% for product in products%}
                    {% if product.product_category == 'Cycling GPS' %}
                        <div class="col-md-6 col-lg-3">
                            <article class="card withCSS h-100">
                                <a href="{{ url_for('main.item', product_id=product.product_detail_id) }}">
                                    <img class="card-img-top card-image"
                                    src="{{url_for('static', filename = 'img/'+product.image)}}"
                                    alt="{{product.productname}}">
                                </a>
                                <div class="card-body">
                                    <h3 class="card-title">{{product.productname}}</h3>
                                    <h5 class="card-text text-success font-weight-light">Stock Status: {{product.stock_status}}</h5>
                                    <h5 class="card-text font-italic">{{"$%.2f"|format(product.price)}}</h5>
                                </div>
                                <div class="card-footer">
                                    <form action="{{url_for('main.order')}}">
                                        <input type="hidden" id="product_id" name="product_id" value="{{product.id}}">
                                        <input class="btn btn-success card-button-CSS" type="submit" value="Add to Cart">
                                    </form>
                                </div>
                            </article>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </section>

        <section class="m-3">
            <div class="category-title-parent">
                <h1 class="category-title" id="fitness-watches">Fitness Watches</h1>
            </div>

            <div class="container-fluid">
                <div class="row">
                    {% for product in products%}
                    {% if product.product_category == 'Fitness Watches' %}
                        <div class="col-md-6 col-lg-3">
                            <article class="card withCSS h-100">
                                <a href="{{ url_for('main.item', product_id=product.product_detail_id) }}">
                                    <img class="card-img-top card-image"
                                    src="{{url_for('static', filename = 'img/'+product.image)}}"
                                    alt="{{product.productname}}">
                                </a>
                                <div class="card-body">
                                    <h3 class="card-title">{{product.productname}}</h3>
                                    <h5 class="card-text text-success font-weight-light">Stock Status: {{product.stock_status}}</h5>
                                    <h5 class="card-text font-italic">${{"%.2f"|format(product.price)}}</h5>
                                </div>
                                <div class="card-footer">
                                    <form action="{{url_for('main.order')}}">
                                        <input type="hidden" id="product_id" name="product_id" value="{{product.id}}">
                                        <input class="btn btn-success card-button-CSS" type="submit" value="Add to Cart">
                                    </form>
                                </div>
                            </article>
                        </div>
                    {% endif %}
                {% endfor %}
                </div>
            </div> 
            
        </section>
{% endblock %}

godfreystore/templates/item.html
{% extends 'base.html' %}

{% block main %}
     <!-- Contains the main content of the website, divided into sections -->
    <main class="content">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{{ url_for('main.index') }}">Home</a></li>
              <li class="breadcrumb-item"><a href="{{ url_for('main.categories', category=product.product_category) }}">{{ product.product_category }}</a></li>
              <li class="breadcrumb-item active" aria-current="page">{{ product.productname }}</li>
            </ol>
          </nav>
          
          <div class="container-fluid">
            <div class="row">
              <div class="col-sm-12 col-md-4">
                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                  <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                  </ol>
                    <div class="carousel-inner" role="listbox">
                      <div class="carousel-item active">
                        <img class="d-block w-100" src="{{url_for('static', filename = 'img/'+product.image)}}" alt="First Image">
                      </div>
                      <div class="carousel-item">
                        <img class="d-block w-100" src="{{url_for('static', filename = 'img/'+product.product_detail.product_detail_image)}}" data-src="holder.js/900x400?theme=industrial" alt="Second Image">
                      </div>
                      <div class="carousel-item">
                        <img class="d-block w-100" src="{{url_for('static', filename = 'img/'+product.image)}}" data-src="holder.js/900x400?theme=industrial" alt="Third Image">
                      </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                      <span class="carousel-control-prev-icon  carousel-btn" aria-hidden="true"></span>
                      <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                      <span class="carousel-control-next-icon" aria-hidden="true"></span>
                      <span class="sr-only">Next</span>
                    </a>
                  </div>
              </div>

              <div class="col-sm-12 col-md-8">
                <div>
                    <h1 class="p-1">{{product.productname}}</h1>
                    <h2 class="p-1 font-italic">${{product.price}}</h2>
                    <h3 class="p-1 text-success font-weight-light">Stock Status: {{product.stock_status}}</h3>
                    <h3 class="p-1">Product Specification</h3>
                    <p class="p-1">
                      {{product.product_detail.product_description}}</p>
                    <form action="{{url_for('main.order')}}">
                        <input type="hidden" id="product_id" name="product_id" value="{{product.id}}">
                        <input class="btn btn-success card-button-CSS" type="submit" value="Add to Cart">
                    </form>

                </div>
              </div>
            </div>
          </div>

          <article>
            <table class="table table-bordered mt-3 mb-3">
                <thead>
                    <tr>
                        <th colspan="2" >Product Specification</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Launch Date</td>
                        <td>{{product.product_detail.launch_date}}</td>
                    </tr>
                    <tr>
                        <td>Bluetooth Support</td>
                        <td>{{product.product_detail.bluetooth_support}}</td>
                    </tr>
                    <tr>
                        <td>Language</td>
                        <td>{{product.product_detail.language}}</td>
                    </tr>
                    <tr>
                        <td>Color</td>
                        <td>{{product.product_detail.color}}</td>
                    </tr>
                    <tr>
                        <td>Made In</td>
                        <td>{{product.product_detail.made_in}}</td>
                    </tr>
                </tbody>
              </table>
            </article>
{% endblock %}

godfreystore/templates/order.html
{% extends 'base.html' %}

{% block main %}
<!-- display contents of user basket -->
<section> 
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{{ url_for('main.index') }}">Home</a></li>
          <li class="breadcrumb-item active" aria-current="page">Shopping Cart</li>
        </ol>
      </nav>

    <div class="container">
        <div class="row col-12 d-flex mt-2 mb-2">
            <h1 class="shopping-cart-title">Shopping Cart</h1>
        </div>

        <!-- each product on seperate row -->
        {% for product in order.products %}
            <div class="row shadow-md my-row mb-3 box-css">
                <div class="col-sm-12 card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-lg-3 col-md-6 col-sm-12">
                                <a href="{{ url_for('main.item', product_id=product.product_detail_id) }}">
                                    <img class="img-thumbnail card-image" src="{{url_for('static', filename=('img/' + product.image))}}">
                                </a>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-12">
                                <!-- Item Description -->
                                <h2>{{product.productname}}</h2>
                                <p class="card-text">Launch Date: {{product.product_detail.launch_date}}</p>
                                <p class="card-text">Bluetooth Support: {{product.product_detail.bluetooth_support}}</p>  
                                <p class="card-text">Language: {{product.product_detail.language}}</p>  
                                <p class="card-text">Made in: {{product.product_detail.made_in}}</p>     
                            </div> 

                            <div class="col-lg-2 col-md-6 col-sm-6">
                                <h2 class="">{{"$%.2f"|format(product.price)}}</h5>
                            </div>

                            <div class="col-lg-1 col-md-6 col-sm-6">
                                <form method="POST" action="{{url_for('main.deleteorderitem')}}">
                                    <input type="hidden" id="id" name="id" value="{{product.id}}">
                                    <button type="submit" class="form-link">
                                        <i class="bi bi-trash"></i> Remove
                                    </button>
                                </form> 
                            </div>


                        </div>                      
                    </div>
                </div>
                <br><br>
                <!-- right column has price and delete button -->
                <div class="col-sm-2">
                <!-- delete item button -->

                </div>
            </div>
        {% endfor %}
        
        <!-- total price and page controls -->
        <section>
            <div class="row co-12 d-flex bg-white checkout-total box-css">
                <div class="col-lg-5 col-md-6 col-sm-6">
                    <h4 class="mt-4">Sub Total {{"$%.2f"|format(total_price)}}</h5>
                </div>
                <div class="col-lg-7 col-md-6 col-sm-6 d-flex mt-4 mb-4 justify-content-end">
                    <a href="{{url_for('main.checkout')}}" class="btn btn-success mr-4"><i class="bi bi-bag"></i> Checkout</a>
                    <a href="{{url_for('main.deleteorder')}}" class="btn btn-danger">Clear Cart</a>
                </div>
            </div>
        </section>
    </div>
</section>

{% endblock %}

godfreystore/templates/search.html
{% extends 'base.html' %}

{% block main %}
     <!-- Contains the main content of the website, divided into sections -->
        <section class="m-3">
            <div class="category-title-parent">
                <h1 class="category-title" id="car-gps">Search Result</h1>
            </div>

            <div class="container-fluid">
                <div class="row">
                    {% for product in product%}
                            <div class="col-md-6 col-lg-3 mt-3">
                                <article class="card withCSS h-100">
                                    <a href="{{ url_for('main.item', product_id=product.product_detail_id) }}">
                                        <img class="card-img-top card-image"
                                        src="{{url_for('static', filename = 'img/'+product.image)}}"
                                        alt="{{product.productname}}">
                                    </a>
                                    <div class="card-body">
                                        <h3 class="card-title">{{product.productname}}</h3>
                                        <h5 class="card-text text-success font-weight-light">Stock Status: {{product.stock_status}}</h5>
                                        <h5 class="card-text font-italic">${{product.price}}</h5>
                                    </div>
                                    <div class="card-footer">
                                        <form action="{{url_for('main.order')}}">
                                            <input type="hidden" id="product_id" name="product_id" value="{{product.id}}">
                                            <input class="btn btn-success card-button-CSS" type="submit" value="Add to Cart">
                                        </form>
                                    </div>
                                </article>
                            </div>
                    {% endfor %}
                </div>
        </section>
{% endblock %}